/**
 * This class is generated by jOOQ
 */
package first_project.helix;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<first_project.helix.tables.records.MemberRecord, java.lang.Long> IDENTITY_MEMBER = Identities0.IDENTITY_MEMBER;
	public static final org.jooq.Identity<first_project.helix.tables.records.TweetRecord, java.lang.Long> IDENTITY_TWEET = Identities0.IDENTITY_TWEET;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<first_project.helix.tables.records.MemberRecord> MEMBER_PKEY = UniqueKeys0.MEMBER_PKEY;
	public static final org.jooq.UniqueKey<first_project.helix.tables.records.MemberRecord> MEMBER_EMAIL_KEY = UniqueKeys0.MEMBER_EMAIL_KEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<first_project.helix.tables.records.MemberRecord, java.lang.Long> IDENTITY_MEMBER = createIdentity(first_project.helix.tables.Member.MEMBER, first_project.helix.tables.Member.MEMBER.ID);
		public static org.jooq.Identity<first_project.helix.tables.records.TweetRecord, java.lang.Long> IDENTITY_TWEET = createIdentity(first_project.helix.tables.Tweet.TWEET, first_project.helix.tables.Tweet.TWEET.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<first_project.helix.tables.records.MemberRecord> MEMBER_PKEY = createUniqueKey(first_project.helix.tables.Member.MEMBER, first_project.helix.tables.Member.MEMBER.ID);
		public static final org.jooq.UniqueKey<first_project.helix.tables.records.MemberRecord> MEMBER_EMAIL_KEY = createUniqueKey(first_project.helix.tables.Member.MEMBER, first_project.helix.tables.Member.MEMBER.EMAIL);
	}
}
