/**
 * This class is generated by jOOQ
 */
package first_project.helix.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Follower extends org.jooq.impl.TableImpl<first_project.helix.tables.records.FollowerRecord> {

	private static final long serialVersionUID = -416343523;

	/**
	 * The singleton instance of <code>public.follower</code>
	 */
	public static final first_project.helix.tables.Follower FOLLOWER = new first_project.helix.tables.Follower();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<first_project.helix.tables.records.FollowerRecord> getRecordType() {
		return first_project.helix.tables.records.FollowerRecord.class;
	}

	/**
	 * The column <code>public.follower.user_id</code>.
	 */
	public final org.jooq.TableField<first_project.helix.tables.records.FollowerRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.follower.following_id</code>.
	 */
	public final org.jooq.TableField<first_project.helix.tables.records.FollowerRecord, java.lang.Long> FOLLOWING_ID = createField("following_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>public.follower</code> table reference
	 */
	public Follower() {
		this("follower", null);
	}

	/**
	 * Create an aliased <code>public.follower</code> table reference
	 */
	public Follower(java.lang.String alias) {
		this(alias, first_project.helix.tables.Follower.FOLLOWER);
	}

	private Follower(java.lang.String alias, org.jooq.Table<first_project.helix.tables.records.FollowerRecord> aliased) {
		this(alias, aliased, null);
	}

	private Follower(java.lang.String alias, org.jooq.Table<first_project.helix.tables.records.FollowerRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, first_project.helix.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public first_project.helix.tables.Follower as(java.lang.String alias) {
		return new first_project.helix.tables.Follower(alias, this);
	}

	/**
	 * Rename this table
	 */
	public first_project.helix.tables.Follower rename(java.lang.String name) {
		return new first_project.helix.tables.Follower(name, null);
	}
}
